config/routes.rb
Rails.application.routes.draw do
  resources :salas
  resources :locals
  resources :ingressos
  get 'adm/index'
  resources :apresentacaos
  resources :classes_eventos
  resources :cidades
  resources :estados
  resources :faixa_etaria
  resources :credit_cards
  root 'welcome#index'
  resources :eventos
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :show]
  get 'adm', to: 'adm#index', as:'adm_painel'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apresentacao.rb
class Apresentacao < ApplicationRecord
    belongs_to :evento
    validates :ingressos_total, presence:true, numericality: { only_integer: true, greater_than: 0 }
    validates :horario, presence:true
    validates :name, presence:true, length: { in: 2..40 } 
    validates :descricao, presence:true, length: { in: 2..1000 }
    before_save :normalize_fields
    private
    def normalize_fields
        self.descricao = self.descricao.titleize
        self.name = self.name.capitalize
    end

end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  validates :cidade_nome, nill: false, length: {in: 4..30}, uniqueness: { scope: :estado_id, case_sensitive: false}

  before_save :normalize_fields

    private
    def normalize_fields
        self.cidade_nome = self.cidade_nome.titleize
    end
end

app/models/classes_evento.rb
class ClassesEvento < ApplicationRecord
    has_many :eventos
    validates :classe, presence: true, uniqueness: {case_sensitive: false} 

    before_save :normalize_fields
    private
    def normalize_fields
        self.classe = self.classe.titleize
    end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
    belongs_to :user
end

app/models/estado.rb
class Estado < ApplicationRecord
    has_many :cidades
    validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {in: 4..30}
    validates :sigla, presence: true, uniqueness: true, length: {is: 2}
    before_save :normalize_fields
  
    private
    def normalize_fields
        self.name = self.name.titleize
        self.sigla = self.sigla.upcase
    end

end

app/models/evento.rb
class Evento < ApplicationRecord
    belongs_to :user
    belongs_to :classes_evento
    belongs_to :faixa_etarium
    has_many :apresentacaos

    before_save :normalize_fields
    # validate :mesmo_evento_na_mesma_data

    validates :title, presence: true, length:{in: 2..30}
    validate :dates_cannot_be_in_the_past


    private
    def normalize_fields
        self.title = self.title.downcase
        self.title = self.title.titleize
        #self.descricao = self.descricao.capitalize
    end

    def mesmo_evento_na_mesma_data
        if Evento.exists?(title: self.title.downcase.titleize, date_begin: self.date_begin.to_date.beginning_of_day..self.date_end.to_date.end_of_day)            
            errors.add(:title, "ja existe")
        end
    end

    def dates_cannot_be_in_the_past
        if (date_begin.present? && date_begin < Date.today)
        errors.add(:date_begin, "can't be in the past")
        end
        if date_end.present? && date_end < Date.today
        errors.add(:date_end, "can't be in the past")
        end

        if date_begin >= date_end
            errors.add(:date_begin, "must begin before end")
        end
    end
end

app/models/faixa_etarium.rb
class FaixaEtarium < ApplicationRecord
    has_many :eventos 
    validates :faixa_etaria, presence: true, uniqueness: {case_sensitive: false}, length: {in: 5..48}
    validates :description, presence: true, length: {in: 6..700}
    before_save :normalize_fields

    private
    def normalize_fields
        self.faixa_etaria = self.faixa_etaria.titleize
        self.description = self.description.capitalize
    end
end

app/models/ingresso.rb
class Ingresso < ApplicationRecord
  belongs_to :apresentacao
  belongs_to :user
end

app/models/local.rb
class Local < ApplicationRecord
  belongs_to :cidade
end

app/models/sala.rb
class Sala < ApplicationRecord
  belongs_to :local
end

app/models/user.rb
class User < ApplicationRecord
  has_many :eventos
  has_one :credit_card
  accepts_nested_attributes_for :credit_card
  validates :cpf, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:number, :security, :expiration)
    end
end

app/helpers/adm_helper.rb
module AdmHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/ingressos_helper.rb
module IngressosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/credit_cards/_form.html.erb
<%= simple_form_for(@credit_card) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :security %>
    <%= f.input :expiration %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing Credit Card</h1>

<%= render 'form', credit_card: @credit_card %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credit Cards</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Security</th>
      <th>Expiration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= credit_card.number %></td>
        <td><%= credit_card.security %></td>
        <td><%= credit_card.expiration %></td>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit Card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New Credit Card</h1>

<%= render 'form', credit_card: @credit_card %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @credit_card.number %>
</p>

<p>
  <strong>Security:</strong>
  <%= @credit_card.security %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @credit_card.expiration %>
</p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>