config/routes.rb
Rails.application.routes.draw do
  resources :salas
  resources :locals
  resources :ingressos
  get 'adm/index'
  resources :apresentacaos
  resources :classes_eventos
  resources :cidades
  resources :estados
  resources :faixa_etaria
  resources :credit_cards
  root 'welcome#index'
  resources :eventos
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :show]
  get 'adm', to: 'adm#index', as:'adm_painel'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apresentacao.rb
class Apresentacao < ApplicationRecord
    belongs_to :evento
    validates :ingressos_total, presence:true, numericality: { only_integer: true, greater_than: 0 }
    validates :horario, presence:true
    validates :name, presence:true, length: { in: 2..40 } 
    validates :descricao, presence:true, length: { in: 2..1000 }
    before_save :normalize_fields
    private
    def normalize_fields
        self.descricao = self.descricao.titleize
        self.name = self.name.capitalize
    end

end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  validates :cidade_nome, nill: false, length: {in: 4..30}, uniqueness: { scope: :estado_id, case_sensitive: false}

  before_save :normalize_fields

    private
    def normalize_fields
        self.cidade_nome = self.cidade_nome.titleize
    end
end

app/models/classes_evento.rb
class ClassesEvento < ApplicationRecord
    has_many :eventos
    validates :classe, presence: true, uniqueness: {case_sensitive: false} 

    before_save :normalize_fields
    private
    def normalize_fields
        self.classe = self.classe.titleize
    end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
    belongs_to :user
end

app/models/estado.rb
class Estado < ApplicationRecord
    has_many :cidades
    validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {in: 4..30}
    validates :sigla, presence: true, uniqueness: true, length: {is: 2}
    before_save :normalize_fields
  
    private
    def normalize_fields
        self.name = self.name.titleize
        self.sigla = self.sigla.upcase
    end

end

app/models/evento.rb
class Evento < ApplicationRecord
    belongs_to :user
    belongs_to :classes_evento
    belongs_to :faixa_etarium
    has_many :apresentacaos

    before_save :normalize_fields
    # validate :mesmo_evento_na_mesma_data

    validates :title, presence: true, length:{in: 2..30}
    validate :dates_cannot_be_in_the_past


    private
    def normalize_fields
        self.title = self.title.downcase
        self.title = self.title.titleize
        #self.descricao = self.descricao.capitalize
    end

    def mesmo_evento_na_mesma_data
        if Evento.exists?(title: self.title.downcase.titleize, date_begin: self.date_begin.to_date.beginning_of_day..self.date_end.to_date.end_of_day)            
            errors.add(:title, "ja existe")
        end
    end

    def dates_cannot_be_in_the_past
        if (date_begin.present? && date_begin < Date.today)
        errors.add(:date_begin, "can't be in the past")
        end
        if date_end.present? && date_end < Date.today
        errors.add(:date_end, "can't be in the past")
        end

        if date_begin >= date_end
            errors.add(:date_begin, "must begin before end")
        end
    end
end

app/models/faixa_etarium.rb
class FaixaEtarium < ApplicationRecord
    has_many :eventos 
    validates :faixa_etaria, presence: true, uniqueness: {case_sensitive: false}, length: {in: 5..48}
    validates :description, presence: true, length: {in: 6..700}
    before_save :normalize_fields

    private
    def normalize_fields
        self.faixa_etaria = self.faixa_etaria.titleize
        self.description = self.description.capitalize
    end
end

app/models/ingresso.rb
class Ingresso < ApplicationRecord
  belongs_to :apresentacao
  belongs_to :user
end

app/models/local.rb
class Local < ApplicationRecord
  belongs_to :cidade
end

app/models/sala.rb
class Sala < ApplicationRecord
  belongs_to :local
end

app/models/user.rb
class User < ApplicationRecord
  has_many :eventos
  has_one :credit_card
  accepts_nested_attributes_for :credit_card
  validates :cpf, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/classes_eventos_controller.rb
class ClassesEventosController < ApplicationController
  before_action :set_classes_evento, only: [:show, :edit, :update, :destroy]

  # GET /classes_eventos
  # GET /classes_eventos.json
  def index
    @classes_eventos = ClassesEvento.order(:classe)
  end

  # GET /classes_eventos/1
  # GET /classes_eventos/1.json
  def show
  end

  # GET /classes_eventos/new
  def new
    @classes_evento = ClassesEvento.new
  end

  # GET /classes_eventos/1/edit
  def edit
  end

  # POST /classes_eventos
  # POST /classes_eventos.json
  def create
    @classes_evento = ClassesEvento.new(classes_evento_params)

    respond_to do |format|
      if @classes_evento.save
        format.html { redirect_to @classes_evento, notice: 'Classes evento was successfully created.' }
        format.json { render :show, status: :created, location: @classes_evento }
      else
        format.html { render :new }
        format.json { render json: @classes_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classes_eventos/1
  # PATCH/PUT /classes_eventos/1.json
  def update
    respond_to do |format|
      if @classes_evento.update(classes_evento_params)
        format.html { redirect_to @classes_evento, notice: 'Classes evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @classes_evento }
      else
        format.html { render :edit }
        format.json { render json: @classes_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classes_eventos/1
  # DELETE /classes_eventos/1.json
  def destroy
    @classes_evento.destroy
    respond_to do |format|
      format.html { redirect_to classes_eventos_url, notice: 'Classes evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classes_evento
      @classes_evento = ClassesEvento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classes_evento_params
      params.require(:classes_evento).permit(:classe)
    end
end

app/helpers/adm_helper.rb
module AdmHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/classes_eventos_helper.rb
module ClassesEventosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/ingressos_helper.rb
module IngressosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/classes_eventos/_form.html.erb
<%= simple_form_for(@classes_evento) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :classe %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/classes_eventos/edit.html.erb
<% if (user_signed_in?)and(current_user.adm == true) %>




<h1>Editing Classes Evento</h1>

<%= render 'form', classes_evento: @classes_evento %>

<%= link_to 'Show', @classes_evento %> |
<%= link_to 'Back', classes_eventos_path %>

<% else %>
  <p>Somente Adm</p>
  <a href="/">Voltar<a>
<% end %>

app/views/classes_eventos/index.html.erb
<% if (user_signed_in?)and(current_user.adm == true) %>





<p id="notice"><%= notice %></p>

<h1>Classes de Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Classe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classes_eventos.each do |classes_evento| %>
      <tr>
        <td><%= classes_evento.classe %></td>
        <td><%= link_to 'Show', classes_evento %></td>
        <td><%= link_to 'Edit', edit_classes_evento_path(classes_evento) %></td>
        <td><%= link_to 'Destroy', classes_evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Classe de Evento', new_classes_evento_path %>
<% else %>
  <p>Somente Adm</p>
  <a href="/">Voltar<a>
<% end %>

app/views/classes_eventos/new.html.erb
<h1>Nova Classe de Evento</h1>

<%= render 'form', classes_evento: @classes_evento %>

<%= link_to 'Back', classes_eventos_path %>

app/views/classes_eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Classe:</strong>
  <%= @classes_evento.classe %>
</p>

<%= link_to 'Edit', edit_classes_evento_path(@classes_evento) %> |
<%= link_to 'Back', classes_eventos_path %>